//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScePhoto {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScePhoto.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guid.
        /// </summary>
        internal static string CommandLineArgsGuid {
            get {
                return ResourceManager.GetString("CommandLineArgsGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Duplicated guid detected. Element: &apos;{1}&apos;. Guid: &apos;{2}&apos;.
        /// </summary>
        internal static string ConvertersDuplicateGuid {
            get {
                return ResourceManager.GetString("ConvertersDuplicateGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Invalid attribute value. Element: &apos;{1}&apos;. Attribute: &apos;{2}&apos;. Value:&apos;{3}&apos;.
        /// </summary>
        internal static string ConvertersInvalidAttributeValue {
            get {
                return ResourceManager.GetString("ConvertersInvalidAttributeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Invalid element value. Element: &apos;{1}&apos;. Value: &apos;{2}&apos;.
        /// </summary>
        internal static string ConvertersInvalidElementValue {
            get {
                return ResourceManager.GetString("ConvertersInvalidElementValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Missing &apos;{1}/{2}&apos; element.
        /// </summary>
        internal static string ConvertersMissingElement {
            get {
                return ResourceManager.GetString("ConvertersMissingElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XPathDocument to MasterFeedContent conversion failed..
        /// </summary>
        internal static string ConvertersXPathDocumentToMasterFeedFailed {
            get {
                return ResourceManager.GetString("ConvertersXPathDocumentToMasterFeedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XPathDocument to PhotoAlbum conversion failed..
        /// </summary>
        internal static string ConvertersXPathDocumentToPhotoAlbumFailed {
            get {
                return ResourceManager.GetString("ConvertersXPathDocumentToPhotoAlbumFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XPathDocument to PhotoGallery conversion failed..
        /// </summary>
        internal static string ConvertersXPathDocumentToPhotoGalleryFailed {
            get {
                return ResourceManager.GetString("ConvertersXPathDocumentToPhotoGalleryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataFeedSource: Absolution URI is required. URI: {0}.
        /// </summary>
        internal static string DataFeedSourceAbsoluteUriRequired {
            get {
                return ResourceManager.GetString("DataFeedSourceAbsoluteUriRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataFeedSource: Unable to access cached data file &apos;{0}&apos;. Error: File does not exist..
        /// </summary>
        internal static string DataFeedSourceCachedDataMissing {
            get {
                return ResourceManager.GetString("DataFeedSourceCachedDataMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataFeedSource: Unable to create ImageSource from data stream. URI: {0}, Error: {1}.
        /// </summary>
        internal static string DataFeedSourceCreateImageSourceFailed {
            get {
                return ResourceManager.GetString("DataFeedSourceCreateImageSourceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataFeedSource: Unable to create text stream reader from data stream. URI: {0}, Error: {1}.
        /// </summary>
        internal static string DataFeedSourceCreateTextDocumentFailed {
            get {
                return ResourceManager.GetString("DataFeedSourceCreateTextDocumentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataFeedSource: Unable to create XML document from data stream. URI: {0}, Error: {1}.
        /// </summary>
        internal static string DataFeedSourceCreateXmlDocumentFailed {
            get {
                return ResourceManager.GetString("DataFeedSourceCreateXmlDocumentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataFeedSource: Get web data request failed for URI &apos;{0}&apos;. Error: {1}.
        /// </summary>
        internal static string DataFeedSourceGetWebDataFailed {
            get {
                return ResourceManager.GetString("DataFeedSourceGetWebDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataFeedSource: Unable to access cached data file &apos;{0}&apos;. Error: {1}.
        /// </summary>
        internal static string DataFeedSourceReadCachedDataFailed {
            get {
                return ResourceManager.GetString("DataFeedSourceReadCachedDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataFeedSource: Unable to save data to cache file &apos;{0}&apos;. Error: {1}.
        /// </summary>
        internal static string DataFeedSourceSaveToCacheFailed {
            get {
                return ResourceManager.GetString("DataFeedSourceSaveToCacheFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataFeedSource: User-defined object that identifies the request is not unique..
        /// </summary>
        internal static string DataFeedSourceUserStateNotUnique {
            get {
                return ResourceManager.GetString("DataFeedSourceUserStateNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataManager: Absolution URI is required. URI: {0}.
        /// </summary>
        internal static string DataManagerAbsoluteUriRequired {
            get {
                return ResourceManager.GetString("DataManagerAbsoluteUriRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataManager: Concurrent data updates are not supported..
        /// </summary>
        internal static string DataManagerConcurrentUpdateNotSupported {
            get {
                return ResourceManager.GetString("DataManagerConcurrentUpdateNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataManager: Load from local cache canceled..
        /// </summary>
        internal static string DataManagerLoadFromCacheCanceled {
            get {
                return ResourceManager.GetString("DataManagerLoadFromCacheCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataManager: Load from local cache completed..
        /// </summary>
        internal static string DataManagerLoadFromCacheCompleted {
            get {
                return ResourceManager.GetString("DataManagerLoadFromCacheCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataManager: Load from local cache started..
        /// </summary>
        internal static string DataManagerLoadFromCacheStarted {
            get {
                return ResourceManager.GetString("DataManagerLoadFromCacheStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync incomplete. Failed to cache {0} item(s)..
        /// </summary>
        internal static string DataManagerSyncIncomplete {
            get {
                return ResourceManager.GetString("DataManagerSyncIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataManager: Data update process canceled..
        /// </summary>
        internal static string DataManagerUpdateCanceled {
            get {
                return ResourceManager.GetString("DataManagerUpdateCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataManager: Data update process completed..
        /// </summary>
        internal static string DataManagerUpdateCompleted {
            get {
                return ResourceManager.GetString("DataManagerUpdateCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataManager: Data update process started..
        /// </summary>
        internal static string DataManagerUpdateStarted {
            get {
                return ResourceManager.GetString("DataManagerUpdateStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SlideShow start index must be greater than zero..
        /// </summary>
        internal static string InvalidSlideShowStartIndex {
            get {
                return ResourceManager.GetString("InvalidSlideShowStartIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0},{1},{2}.
        /// </summary>
        internal static string LoggerMessageFormat {
            get {
                return ResourceManager.GetString("LoggerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string LoggerMessageTypeError {
            get {
                return ResourceManager.GetString("LoggerMessageTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FatalError.
        /// </summary>
        internal static string LoggerMessageTypeFatalError {
            get {
                return ResourceManager.GetString("LoggerMessageTypeFatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string LoggerMessageTypeInformation {
            get {
                return ResourceManager.GetString("LoggerMessageTypeInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string LoggerMessageTypeWarning {
            get {
                return ResourceManager.GetString("LoggerMessageTypeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigator: Duplicate child navigator guid found.
        /// </summary>
        internal static string NavigatorDuplicateGuid {
            get {
                return ResourceManager.GetString("NavigatorDuplicateGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Album containing searched photos.
        /// </summary>
        internal static string SearchDescription {
            get {
                return ResourceManager.GetString("SearchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchName {
            get {
                return ResourceManager.GetString("SearchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScePhotoSettings are not initialized..
        /// </summary>
        internal static string SettingsNotInitialized {
            get {
                return ResourceManager.GetString("SettingsNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SlideShow must have an album associated with Photo.
        /// </summary>
        internal static string SlideShowMissingAlbum {
            get {
                return ResourceManager.GetString("SlideShowMissingAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog is visible..
        /// </summary>
        internal static string ViewManagerInvalidOperationDialogVisible {
            get {
                return ResourceManager.GetString("ViewManagerInvalidOperationDialogVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewManager: MissingItemError on navigation: {0}.
        /// </summary>
        internal static string ViewManagerMissingItemError {
            get {
                return ResourceManager.GetString("ViewManagerMissingItemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewManager: Navigated to path: {0}.
        /// </summary>
        internal static string ViewManagerNavigated {
            get {
                return ResourceManager.GetString("ViewManagerNavigated", resourceCulture);
            }
        }
    }
}
