//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project. 
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc. 
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File". 
// You do not need to add suppressions to this file manually. 

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1001:TypesThatOwnDisposableFieldsShouldBeDisposable", Scope = "type", Target = "ScePhotoViewer.ScePhotoViewerApplication")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "ScePhotoViewer.SingleInstance.#GetCommandLineArgs()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "ScePhotoViewer.SubscriptionServiceManager.#AddServiceChannelHandlers()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "ScePhotoViewer.SubscriptionServiceManager.#ConnectToServiceChannel()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "ScePhotoViewer.SubscriptionServiceManager.#DataManager_UpdateCompleted(System.Object,System.ComponentModel.AsyncCompletedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "ScePhotoViewer.SubscriptionServiceManager.#DisconnectFromServiceChannel()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "ScePhotoViewer.SubscriptionServiceManager.#IsServiceUpdateInProgress")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "ScePhotoViewer.SubscriptionServiceManager.#NotifyUpdateStarted()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1049:TypesThatOwnNativeResourcesShouldBeDisposable", Scope = "type", Target = "ScePhotoViewer.NativeMethods+WNDCLASSEX")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1049:TypesThatOwnNativeResourcesShouldBeDisposable", Scope = "type", Target = "ScePhotoViewer.SplashScreen")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId = "offset", Scope = "member", Target = "ScePhotoViewer.FilmStripPanel.#SetHorizontalOffset(System.Double)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId = "offset", Scope = "member", Target = "ScePhotoViewer.FilmStripPanel.#SetVerticalOffset(System.Double)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId = "offset", Scope = "member", Target = "ScePhotoViewer.RowScrollingPanel.#SetHorizontalOffset(System.Double)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId = "offset", Scope = "member", Target = "ScePhotoViewer.RowScrollingPanel.#SetVerticalOffset(System.Double)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId = "offset", Scope = "member", Target = "ScePhotoViewer.RowScrollingPanel.#SetVerticalOffset(System.Double,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId = "viewingMode", Scope = "member", Target = "ScePhotoViewer.MainWindow.#GetNextViewingMode(ScePhotoViewer.ViewingMode)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope = "member", Target = "ScePhotoViewer.ApplicationInputHandler.#GetApplicationNavigationActionForKeyEvent(System.Windows.Input.KeyEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "CounterClockwise", Scope = "member", Target = "ScePhotoViewer.PhotoDisplayControl.#RotatePhotoCounterClockwiseCommand")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "CounterClockwise", Scope = "member", Target = "ScePhotoViewer.PhotoDisplayControl.#RotatePhotoDisplayCounterClockwise()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "FilmStrip", Scope = "member", Target = "ScePhotoViewer.FilmStripControl.#FilmStripBrush")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "FilmStrip", Scope = "member", Target = "ScePhotoViewer.FilmStripControl.#FilmStripBrushProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "FilmStrip", Scope = "type", Target = "ScePhotoViewer.FilmStripControl")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "FilmStrip", Scope = "type", Target = "ScePhotoViewer.FilmStripPanel")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "Toolbar", Scope = "type", Target = "ScePhotoViewer.PhotoViewerToolbarControl")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Sce")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Sce", Scope = "namespace", Target = "ScePhotoViewer")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Sce", Scope = "type", Target = "ScePhotoViewer.SampleScePhotoSettings")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Sce", Scope = "type", Target = "ScePhotoViewer.ScePhotoMain")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Sce", Scope = "type", Target = "ScePhotoViewer.ScePhotoViewerApplication")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Sce", Scope = "type", Target = "ScePhotoViewer.ScePhotoViewerSettings")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "IDs", Scope = "type", Target = "ScePhotoViewer.PhotoTagIDsToStringConverter")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "ScePhotoViewer.SingleInstance+IPCRemoteService.#InvokeFirstInstance(System.Collections.Generic.IList`1<System.String>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2001:AvoidCallingProblematicMethods", MessageId = "System.GC.Collect", Scope = "member", Target = "ScePhotoViewer.GarbageCollectCommand.#ExecuteInternal(System.Object)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope = "member", Target = "ScePhotoViewer.NativeMethods+WNDCLASSEX.#hCursor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope = "member", Target = "ScePhotoViewer.SplashScreen.#gdiPlusToken")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope = "member", Target = "ScePhotoViewer.SplashScreen.#hBuffer")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope = "member", Target = "ScePhotoViewer.SplashScreen.#splashScreenHwnd")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "e", Scope = "member", Target = "ScePhotoViewer.MainWindow.#OnJournalBackNavigationKeyOverride(System.Windows.Input.ExecutedRoutedEventArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA1806:DoNotIgnoreMethodResults", MessageId = "ScePhotoViewer.NativeMethods.GdipCreateBitmapFromStream(System.Runtime.InteropServices.ComTypes.IStream,System.IntPtr@)", Scope = "member", Target = "ScePhotoViewer.SplashScreen.#GetHBitmapFromResource(System.IntPtr,System.String,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA1806:DoNotIgnoreMethodResults", MessageId = "ScePhotoViewer.NativeMethods.GdipCreateHBITMAPFromBitmap(System.IntPtr,System.IntPtr@,System.Int32)", Scope = "member", Target = "ScePhotoViewer.SplashScreen.#GetHBitmapFromResource(System.IntPtr,System.String,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA1806:DoNotIgnoreMethodResults", MessageId = "ScePhotoViewer.NativeMethods.GdiplusShutdown(System.IntPtr)", Scope = "member", Target = "ScePhotoViewer.SplashScreen.#Close()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA1806:DoNotIgnoreMethodResults", MessageId = "ScePhotoViewer.NativeMethods.GdiplusStartup(System.IntPtr@,ScePhotoViewer.NativeMethods+StartupInput@,ScePhotoViewer.NativeMethods+StartupOutput@)", Scope = "member", Target = "ScePhotoViewer.SplashScreen.#GetHBitmapFromResource(System.IntPtr,System.String,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA1806:DoNotIgnoreMethodResults", MessageId = "ScePhotoViewer.NativeMethods.GetBitmapInformation(System.IntPtr,System.Int32,ScePhotoViewer.NativeMethods+BITMAP@)", Scope = "member", Target = "ScePhotoViewer.SplashScreen.#Open()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA1806:DoNotIgnoreMethodResults", MessageId = "ScePhotoViewer.NativeMethods.ReleaseDC(System.IntPtr,System.IntPtr)", Scope = "member", Target = "ScePhotoViewer.SplashScreen.#SelectBitmap(System.IntPtr,System.Int32,System.Int32,System.Int32,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "ScePhotoViewer.GalleryHomeControl.#FirstAlbumPhotoThumbnails")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "ScePhotoViewer.GalleryHomeControl.#RightListPhotoAlbumNavigators")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "ScePhotoViewer.GalleryHomeControl.#SecondAlbumPhotoThumbnails")]
