//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project. 
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc. 
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File". 
// You do not need to add suppressions to this file manually. 

// Suppressions relating to identifier spelling where spelling was judged to be correct or necessary.
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "type", Target = "TransitionEffects.PixelateInTransitionEffect", MessageId = "Pixelate")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "type", Target = "TransitionEffects.PixelateOutTransitionEffect", MessageId = "Pixelate")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", Scope = "type", Target = "TransitionEffects.PixelateTransitionEffect", MessageId = "Pixelate")]

// Suppressions relating to 'Slideshow' being a compound word, in the application it is treated as two words 'Slide Show'. This is a matter of usage. 
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", Scope = "type", Target = "ScePhotoViewer.PhotoSlideShowControl", MessageId = "SlideShow")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", Scope = "member", Target = "ScePhotoViewer.PhotoSlideShowControl.#PhotoSlideShowProperty", MessageId = "SlideShow")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", Scope = "member", Target = "ScePhotoViewer.PhotoSlideShowControl.#PhotoSlideShow", MessageId = "SlideShow")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", Scope = "type", Target = "ScePhoto.Data.PhotoSlideShow", MessageId = "SlideShow")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", Scope = "type", Target = "ScePhoto.View.PhotoSlideShowNavigator", MessageId = "SlideShow")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", Scope = "type", Target = "ScePhoto.View.PhotoSlideShowNavigator", MessageId = "SlideShow")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", Scope = "member", Target = "ScePhoto.View.PhotoSlideShowNavigator.#SlideShowGuid", MessageId = "SlideShow")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", Scope = "member", Target = "ScePhoto.View.PhotoSlideShowNavigator.#.ctor(ScePhoto.Data.PhotoSlideShow)", MessageId = "SlideShow")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", Scope = "member", Target = "ScePhoto.View.NavigationCommands.#NavigateToPhotoSlideShowCommand", MessageId = "SlideShow")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", Scope = "type", Target = "ScePhoto.View.NavigateToPhotoSlideShowCommand", MessageId = "SlideShow")]